
name: Deploy

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v2

      - name: FTP Deploy

        uses: peter-evans/upload-ftp@v3

        with:

          server: ${{ secrets.FTP_SERVER }}

          username: ${{ secrets.FTP_USERNAME }}

          password: ${{ secrets.FTP_PASSWORD }}

          port: 2022

          protocol: sftp

          local-dir: ./
          
          server-dir: ./Bot/
