
name: Deploy

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v2

      - name: FTP Deploy

        uses: jakejarvis/ftp-deploy-action@3.1.1

        with:

          server: ${{ secrets.SERVER }}

          username: ${{ secrets.USERNAME }}

          password: ${{ secrets.PASSWORD }}

          server-dir: . 

          local-dir: ./

          exclude: .git*

          timeout: 600000
